name: Pull Request Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build-check:
    name: Build and Release
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.2"

      - name: Test
        run: |
          go test github.com/anasrar/config-init/cmd/config-init/configs

      - name: Build
        run: |
          git rev-parse --short HEAD > cmd/config-init/VERSION.txt
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            bin/*
