name: Build (Release)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        default: "vx.x.x"

jobs:
  build-release:
    name: Build and Release
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.2"

      - name: Test
        run: |
          go test github.com/anasrar/config-init/cmd/config-init/configs

      - name: Build
        run: |
          echo ${{ inputs.version }} > cmd/config-init/VERSION.txt
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Create Release and Upload Artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: false
          tag: ${{ inputs.version }}
          bodyFile: RELEASE.md
          artifacts: bin/*
